// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtZHHK7EN03FHb2su1Pc8mgZX8jK1dK0M',
    appId: '1:337493064108:web:dae354cf1acc7af2fc6209',
    messagingSenderId: '337493064108',
    projectId: 'ystfamily-prod',
    authDomain: 'ystfamily-prod.firebaseapp.com',
    storageBucket: 'ystfamily-prod.appspot.com',
    measurementId: 'G-R46DNJ85KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFqYNa8KddqKAw7n9bP4HLB_Hb4tciuI',
    appId: '1:337493064108:android:52bcf7a872e42385fc6209',
    messagingSenderId: '337493064108',
    projectId: 'ystfamily-prod',
    storageBucket: 'ystfamily-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFhCqlq4Hsl4mAJINEHJ2P56DD_RfuXS0',
    appId: '1:337493064108:ios:6d777ee2b90effb4fc6209',
    messagingSenderId: '337493064108',
    projectId: 'ystfamily-prod',
    storageBucket: 'ystfamily-prod.appspot.com',
    iosBundleId: 'com.kodewizzard.ystfamily',
  );
}
